import { z } from 'zod';
const date=z.string().refine(s=>s==='' || (/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s),'Tanggal tidak valid');
export const taskSchema=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(250),chapter:z.number().int().min(1).max(5),subchapter:z.string().max(150),status:z.number().int().min(0).max(4),due:date,note:z.string().max(2000)}).strict();
export const sessionSchema=z.object({id:z.number().int().min(1).max(50),advisor:z.string().max(80).default(''),date,material:z.string().max(2000),feedback:z.string().max(4000),followup:z.string().max(4000),prepared:z.boolean(),met:z.boolean(),followed:z.boolean()}).strict();
export const logSchema=z.object({id:z.string().min(1).max(100),date:date.refine(s=>s!==''),category:z.string().regex(/^(Bab [1-5]|Bimbingan)$/),text:z.string().trim().min(1).max(2000)}).strict();
export const resourceSchema=z.object({id:z.string().min(1).max(100),label:z.string().trim().min(1).max(100),type:z.enum(['Drive','Docs','Sheets','Lainnya']),url:z.string().url().max(2000)}).strict();
export const trackerSchema=z.object({name:z.string().trim().min(1).max(80),project:z.string().trim().min(1).max(160),program:z.string().max(120).default('Film dan Televisi'),studentId:z.string().max(80).default(''),thesisTitle:z.string().max(300).default(''),profilePhoto:z.string().max(750000).refine(v=>v===''||/^data:image\/(jpeg|png|webp);base64,/.test(v),'Foto profil tidak valid').default(''),advisors:z.array(z.string().trim().min(1).max(80)).min(1).max(8).default(['Dosen Pembimbing 1','Dosen Pembimbing 2']),writingWeight:z.number().int().min(0).max(100),reminderDays:z.number().int().min(0).max(30).default(3),resources:z.array(resourceSchema).max(50).default([]),tasks:z.array(taskSchema).max(2000),sessions:z.array(sessionSchema).min(1).max(50),logs:z.array(logSchema).max(5000)}).strict().superRefine((s,c)=>{for(const [field,items] of [['tasks',s.tasks],['sessions',s.sessions],['logs',s.logs],['resources',s.resources]] as const){if(new Set(items.map(x=>x.id)).size!==items.length)c.addIssue({code:'custom',message:'ID harus unik',path:[field]});}});
export type Task=z.infer<typeof taskSchema>;
export type Session=z.infer<typeof sessionSchema>;
export type Log=z.infer<typeof logSchema>;
export type Resource=z.infer<typeof resourceSchema>;
export type TrackerData=z.infer<typeof trackerSchema>;
export type Snapshot={data:TrackerData;revision:number;updatedAt:string};
export const statuses=['Belum mulai','Mulai dikerjakan','Draf awal','Revisi / finalisasi','Selesai'];
export const chapterNames=['Pendahuluan','Kajian & referensi','Konsep penciptaan','Pembahasan karya','Penutup'];
const templates=[['Petakan masalah penciptaan','Tulis latar belakang','Rumuskan tujuan penciptaan','Susun manfaat penciptaan','Rapikan alur argumentasi'],['Ringkas satu sumber teori','Petakan konsep sinematografi','Uraikan pergerakan kamera','Bandingkan karya rujukan','Periksa kutipan dan sitasi'],['Petakan konsep visual','Jelaskan motivasi kamera','Tulis rancangan penciptaan','Susun tahapan kerja','Cek konsistensi konsep'],['Susun bahan pembahasan karya','Pilih shot untuk dianalisis','Hubungkan shot dengan konsep','Catat evaluasi penciptaan','Rapikan pembahasan'],['Buat kerangka kesimpulan','Catat temuan utama','Tulis kesimpulan','Tulis saran','Periksa kesesuaian tujuan']];
export function initialTracker():TrackerData{return {name:'Pengguna Skripsync',project:'Tugas Akhir',program:'',studentId:'',thesisTitle:'',profilePhoto:'',advisors:['Dosen Pembimbing 1','Dosen Pembimbing 2'],writingWeight:80,reminderDays:3,resources:[],tasks:[],sessions:[{id:1,advisor:'Dosen Pembimbing 1',date:'',material:'',feedback:'',followup:'',prepared:false,met:false,followed:false}],logs:[]};}
export function sessionProgress(s:Session){return (s.prepared?30:0)+(s.met?40:0)+(s.followed?30:0);}
export function metrics(d:TrackerData){const chapters=Array.from({length:5},(_,i)=>{const t=d.tasks.filter(t=>t.chapter===i+1);return {id:i+1,count:t.length,done:t.filter(t=>t.status===4).length,progress:t.length?t.reduce((v,t)=>v+t.status*25,0)/t.length:0};});const writing=chapters.reduce((v,c)=>v+c.progress,0)/5;const consultation=d.sessions.reduce((v,s)=>v+sessionProgress(s),0)/d.sessions.length;return {chapters,writing,consultation,total:(writing*d.writingWeight+consultation*(100-d.writingWeight))/100,done:d.tasks.filter(t=>t.status===4).length,started:d.tasks.filter(t=>t.status>0&&t.status<4).length,consultDone:d.sessions.filter(s=>sessionProgress(s)===100).length};}
export function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
export function formatDate(d:string){return d?new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z')):'Belum dijadwalkan';}
export function weeklyLogs(logs:Log[]){const now=new Date(localDate()+'T12:00:00Z');now.setUTCDate(now.getUTCDate()-(now.getUTCDay()+6)%7);return Array.from({length:6},(_,i)=>{const start=new Date(now);start.setUTCDate(start.getUTCDate()-(5-i)*7);const end=new Date(start);end.setUTCDate(end.getUTCDate()+7);const a=start.toISOString().slice(0,10),b=end.toISOString().slice(0,10);return {label:new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',timeZone:'UTC'}).format(start),count:logs.filter(l=>l.date>=a&&l.date<b).length};});}
